# Generated by Django 4.2.2 on 2023-06-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_film_remove_user_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Film",
        ),
    ]
